version: 2.1
orbs:
  node: circleci/node@4.0.1

workflows:
  test:
    jobs:
      - node/test:
          run-command: accessibility-check
          run-command: style-check
          run-command: test
